### PR TITLE
add jaap

### PR DESCRIPTION
**Pull request by jgroeneveld**
hi lasse,
i would like to be on the list as well :)

i added it to the empty one. once you revert back to the full list, i would be happy if you merge it :)

### CODE REVIEW

**Comment by lassediercks** [comment]
Hey Jaap, sure thing! will do

**Comment by lassediercks** [comment]
due to a merge conflict I added you by myself :D welcome https://github.com/lassediercks/list-of-tech-freelancers-in-germany/commit/1fe4333082ebf856840b495396fcc6ef8e1e9fa8

**Comment by jgroeneveld** [comment]
thanks @lassediercks

**Comment by jgroeneveld** [comment]
@lassediercks  i also added me to the remote list but in the end its probably not a big deal.

**Pull request closed without merging**
