### PR TITLE
add Lea

### PR DESCRIPTION
**Pull request by terabaud**

### CODE REVIEW

**Comment by LemonAndroid** [comment]
@terabaud why did you close the pr? it took some time to merge my pr as well.

**Comment by terabaud** [comment]
A case of 'maybe I-am-not-tech-enough-to-get-on-the-list' imposter syndrome

**Comment by LemonAndroid** [comment]
That's a thing? 🤣

**Comment by LemonAndroid** [comment]
pinging @lassediercks

**Comment by lassediercks** [comment]
so sorry, here wo go. Welcome <3

**Pull request merged**
